### PR TITLE
feat: convert to Typescript

### PR DESCRIPTION
**Pull request by mogusbi-motech**
Convert the logging package into TypeScript and automatically publish it to Nexus.

## Developer notes
To migrate existing apps they will need to change the import from `applications-common-logging` to `@vmd/logging`. Other then that it should be a non-breaking change so it should continue to function as before.

Existing apps can continue to point to the old version via GitHub as they currently do until that migration can occur

### CODE REVIEW

**Review by meyumeapps — APPROVED** [review]
LGTM 👍

**Review by richmilton — APPROVED** [review]
LGTM

**Review by simon-technocloud — APPROVED** [review]
LGTM

**Pull request merged**
